/* 
 * TrackServer
 *
 * Server for People Tracking System
 *
 * OpenAPI spec version: 1.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = PTClient.IO.Swagger.Client.SwaggerDateConverter;

namespace PTClient.IO.Swagger.Model
{
    /// <summary>
    /// InlineResponse201
    /// </summary>
    [DataContract]
    public partial class InlineResponse201 :  IEquatable<InlineResponse201>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse201" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineResponse201() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse201" /> class.
        /// </summary>
        /// <param name="Confirm">Confirm (required).</param>
        /// <param name="IsCaptain">IsCaptain (required).</param>
        public InlineResponse201(bool? Confirm = default(bool?), bool? IsCaptain = default(bool?))
        {
            // to ensure "Confirm" is required (not null)
            if (Confirm == null)
            {
                throw new InvalidDataException("Confirm is a required property for InlineResponse201 and cannot be null");
            }
            else
            {
                this.Confirm = Confirm;
            }
            // to ensure "IsCaptain" is required (not null)
            if (IsCaptain == null)
            {
                throw new InvalidDataException("IsCaptain is a required property for InlineResponse201 and cannot be null");
            }
            else
            {
                this.IsCaptain = IsCaptain;
            }
        }
        
        /// <summary>
        /// Gets or Sets Confirm
        /// </summary>
        [DataMember(Name="confirm", EmitDefaultValue=false)]
        public bool? Confirm { get; set; }

        /// <summary>
        /// Gets or Sets IsCaptain
        /// </summary>
        [DataMember(Name="isCaptain", EmitDefaultValue=false)]
        public bool? IsCaptain { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse201 {\n");
            sb.Append("  Confirm: ").Append(Confirm).Append("\n");
            sb.Append("  IsCaptain: ").Append(IsCaptain).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse201);
        }

        /// <summary>
        /// Returns true if InlineResponse201 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse201 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse201 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Confirm == input.Confirm ||
                    (this.Confirm != null &&
                    this.Confirm.Equals(input.Confirm))
                ) && 
                (
                    this.IsCaptain == input.IsCaptain ||
                    (this.IsCaptain != null &&
                    this.IsCaptain.Equals(input.IsCaptain))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Confirm != null)
                    hashCode = hashCode * 59 + this.Confirm.GetHashCode();
                if (this.IsCaptain != null)
                    hashCode = hashCode * 59 + this.IsCaptain.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
