/* 
 * TrackServer
 *
 * Server for People Tracking System
 *
 * OpenAPI spec version: 1.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = PTClient.IO.Swagger.Client.SwaggerDateConverter;
using PTClient.SharedResources;

namespace PTClient.IO.Swagger.Model
{
    /// <summary>
    /// InlineResponse2022
    /// </summary>
    [DataContract]
    public partial class InlineResponse2022 :  IEquatable<InlineResponse2022>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse2022" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineResponse2022() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse2022" /> class.
        /// </summary>
        /// <param name="Turbines">Turbines (required).</param>
        public InlineResponse2022(List<TurbineItem> Turbines = default(List<TurbineItem>))
        {
            // to ensure "Turbines" is required (not null)
            if (Turbines == null)
            {
                throw new InvalidDataException("Turbines is a required property for InlineResponse2022 and cannot be null");
            }
            else
            {
                this.Turbines = Turbines;
            }
        }
        
        /// <summary>
        /// Gets or Sets Turbines
        /// </summary>
        [DataMember(Name="turbines", EmitDefaultValue=false)]
        public List<TurbineItem> Turbines { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse2022 {\n");
            sb.Append("  Turbines: ").Append(Turbines).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse2022);
        }

        /// <summary>
        /// Returns true if InlineResponse2022 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse2022 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse2022 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Turbines == input.Turbines ||
                    this.Turbines != null &&
                    this.Turbines.SequenceEqual(input.Turbines)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Turbines != null)
                    hashCode = hashCode * 59 + this.Turbines.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
